# Generated by Django 6.0.5 on 2026-06-16 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0004_quizattempt_quizattemptresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='time_taken_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
