# Generated by Django 6.0.5 on 2026-06-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0005_quizattempt_time_taken_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='slug',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
