# Generated by Django 6.0.5 on 2026-06-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0006_examattempt_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='slug',
            field=models.SlugField(blank=True, max_length=160),
        ),
    ]
