# Generated by Django 6.0.5 on 2026-06-27 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0008_student_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_key', models.CharField(max_length=200)),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_notifications', to='student_portal.student')),
            ],
            options={
                'unique_together': {('student', 'notif_key')},
            },
        ),
    ]
