# Generated by Django 6.0.5 on 2026-06-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0007_submodule_question_submodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='submodule',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
    ]
