# Generated by Django 6.0.5 on 2026-06-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0008_submodule_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submodule',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='submodules/'),
        ),
    ]
