# Generated by Django 6.0.5 on 2026-06-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0009_alter_submodule_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='submodules',
            field=models.ManyToManyField(blank=True, related_name='exams', to='student_management.submodule'),
        ),
    ]
