# Generated by Django 6.0.5 on 2026-06-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0010_exam_submodules'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtype',
            name='custom_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
