# Generated by Django 6.0.5 on 2026-06-11 11:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0011_examtype_custom_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('duration_days', models.PositiveIntegerField(default=30, help_text='Validity period in days (e.g. 30, 90, 365).', validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exams', models.ManyToManyField(blank=True, related_name='subscription_plans', to='student_management.exam')),
                ('subjects', models.ManyToManyField(blank=True, related_name='subscription_plans', to='student_management.subject')),
                ('submodules', models.ManyToManyField(blank=True, related_name='subscription_plans', to='student_management.submodule')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
    ]
