# Generated by Django 6.0.5 on 2026-06-12 07:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0014_payment_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
