# Generated by Django 6.0.5 on 2026-06-12 09:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0015_subscriptionplan_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
