# Generated by Django 6.0.5 on 2026-06-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0016_alter_subscriptionplan_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='exam_images/'),
        ),
    ]
