# Generated by Django 6.0.5 on 2026-06-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0017_exam_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='subjects/'),
        ),
    ]
